services:
  web-client:
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.web-client-release.rule=Host(`eyebuild.us`) && PathPrefix(`/`)
      - traefik.http.routers.web-client-release.entrypoints=https
      - traefik.http.services.web-client-release.loadbalancer.server.port=3000
      - io.portainer.accesscontrol.teams=eyebuild
    networks:
      - release
      - traefik

  core:
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.backend-release.rule=Host(`eyebuild.us`) && PathPrefix(`/core`)
      - traefik.http.routers.backend-release.entrypoints=https
      - traefik.http.services.backend-release.loadbalancer.server.port=8000
      - io.portainer.accesscontrol.teams=eyebuild
    networks:
      - release
      - traefik

  mongo:
    volumes:
      - /data/eyebuild/release/mongo:/data/db
    networks:
      - release

networks:
  traefik:
    external:
      name: traefik
  release: