export const FIRSTNAMES = [
  'John',
  'Jane',
  'Michael',
  'Sarah',
  'David',
  'Emma',
  'Chris',
  'Sophia',
  'Daniel',
  'Olivia',
  'James',
  'Mary',
  'Robert',
  'Linda',
  'William',
  'Patricia',
  'Thomas',
  'Elizabeth',
  'Charles',
  'Margaret',
  'Christopher',
  'Jessica',
  'Joseph',
  'Dorothy',
  'Daniel',
  'Helen',
  'Ethan',
  'Ava',
  'Benjamin',
  'Mia',
  'Lucas',
  'Charlotte',
  'Samuel',
  'Amelia',
  'Henry',
  'Grace',
  'Alexander',
  'Lily',
  'Jack',
  'Sophie',
];

export const LASTNAMES = [
  'Smith',
  'Johnson',
  'Brown',
  'Williams',
  'Jones',
  'Miller',
  'Davis',
  'García',
  'Rodriguez',
  'Martinez',
  'Anderson',
  'Thomas',
  'Taylor',
  'Moore',
  'Jackson',
  'White',
  'Harris',
  'Martin',
  'Thompson',
  'Garcia',
  'Martinez',
  'Robinson',
  'Clark',
  'Lewis',
  'Lee',
  'Walker',
  'Hall',
  'Young',
  'Allen',
  'King',
  'Scott',
  'Green',
  'Baker',
  'Adams',
  'Nelson',
  'Carter',
  'Mitchell',
  'Perez',
  'Roberts',
  'Evans',
];

export const COMPANIES = [
  'Tech Corp',
  'Innovate LLC',
  'Global Inc.',
  'Future Tech',
  'NextGen Solutions',
  'Dynamic Systems',
  'Creative Tech',
  'Advanced Technologies',
  'Quantum Innovations',
  'Synergy Global',
  'Tech Nexus',
  'Future Vision',
  'Pioneers Ltd.',
  'Hyper Tech',
  'Smart Solutions',
  'Visionary Technologies',
  'NextTech Enterprises',
  'Infinite Labs',
  'AlphaTech',
  'RedTech Innovations',
  'Cloud Innovations',
  'TechTrail',
  'SmartGear Corp.',
  'Fusion Systems',
  'Green Innovations',
  'Digital Trends',
  'PeakTech',
  'InnovationWorks',
  'CyberLabs',
  'TechSprint',
  'AI Hub',
  'NextWave Technologies',
];

export const DOMAINS = [
  'example.com',
  'test.com',
  'domain.org',
  'techmail.com',
  'innovate.net',
  'globalco.biz',
  'futuretech.co',
  'nextgen.io',
  'smartsolutions.us',
  'cyberlabs.org',
  'quantumhub.com',
  'digitaltech.net',
  'pioneerscorp.org',
  'synergytech.com',
  'cloudlabs.io',
  'visionarytech.us',
  'alpha-inc.co',
  'redtech.io',
  'infinitelabs.net',
  'smartgear.org',
  'fusiontech.us',
  'nextwave.biz',
  'peaklab.net',
  'fusionlabs.org',
  'aitech.com',
  'systechsolutions.net',
  'cloudsolutions.co',
  'digitalinnovations.com',
  'techsolutions.biz',
  'futureinc.net',
  'nextgenmail.org',
  'innovativecloud.com',
  'hypercloud.us',
  'techwaves.co',
  'creativesolutions.io',
];
