services:

  web-client:
    build:
      context: ../../services/web-client
      dockerfile: Dockerfile.dev
    volumes:
      - "../../services/web-client:/app"
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
      NEXT_PUBLIC_ADMIN_EMAIL: ${NEXT_PUBLIC_ADMIN_EMAIL}
    networks:
      - traefik

  core:
    restart: always
    build:
      context: ../../services/core
      dockerfile: Dockerfile.dev
    volumes:
      - "../../services/core:/app"
    ports:
      - "8000:8000"
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
      MONGO_URL: ${MONGO_URL}
      COOKIE_SECRET: ${COOKIE_SECRET}
      CLIENT_URL: ${CLIENT_URL}
      SUPERADMIN_USERNAME: ${SUPERADMIN_USERNAME}
      SUPERADMIN_EMAIL: ${SUPERADMIN_EMAIL}
      SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}
      SUPERADMIN_PHONE: ${SUPERADMIN_PHONE}
    depends_on:
      - mongo
    networks:
      - traefik
  
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - /data/eyebuild/mongo:/data/db
    networks:
      - traefik

  traefik:
    build: traefik
    restart: always
    networks:
      - traefik
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro


networks:
  traefik:
    driver: bridge