networks:
  traefik:
    name: traefik

services:
  traefik:
    build: ${CI_PROJECT_DIR}/deploy/staging/traefik
    container_name: traefik
    restart: always
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: "traefik/whoami"
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.whoami.rule=Host(`whoami-eyebuild.staging.forasoft.com`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=http"
      - "traefik.http.services.whoami.loadbalancer.server.port=3000"
